# Generated by Django 3.0.4 on 2020-03-10 03:12

from django.db import migrations, models
import django.db.models.deletion
import documento.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('serie', models.CharField(max_length=255)),
                ('n_documento', models.CharField(max_length=255, verbose_name='Nº Documento')),
                ('ruc', models.CharField(max_length=12, validators=[documento.models.validar_ruc], verbose_name='RUC')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('documento', models.CharField(blank=True, choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('comprobante', 'Comprobante'), ('nota_de_credito', 'Nota de Credito'), ('nota_de_debito', 'Nota de Debito')], max_length=50, null=True)),
                ('moneda', models.CharField(choices=[('soles', 'Soles'), ('dolar', 'Dolar'), ('euro', 'Euro')], default='soles', max_length=50)),
                ('fecha', models.DateField(validators=[documento.models.verificar_fecha])),
                ('tc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Actualizar TC')),
                ('tc_texto', models.TextField(blank=True, null=True)),
                ('actualizar_tc', models.BooleanField(default=True)),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('actualizar_ruc', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
