# Generated by Django 3.0.4 on 2020-03-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_auto_20200309_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='primer_gurdado',
            field=models.BooleanField(default=True),
        ),
    ]
