# Generated by Django 3.0.4 on 2020-03-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_documento_primer_gurdado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tc_texto',
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_cambio',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default=1, max_length=255, verbose_name='Tipo de Cambio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='tc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor TC'),
        ),
    ]
