# Generated by Django 3.0.4 on 2020-03-29 21:35

from django.db import migrations, models
import documento.models


class Migration(migrations.Migration):

    dependencies = [
        ('detalle', '0003_remove_detalle_documento'),
        ('documento', '0004_auto_20200309_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='detalles',
            field=models.ManyToManyField(blank=True, to='detalle.detalle'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='n_documento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ruc',
            field=models.CharField(max_length=11, validators=[documento.models.validar_ruc], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='serie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
