# Generated by Django 3.0.4 on 2020-03-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Cantidad')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
