# Generated by Django 3.0.4 on 2020-03-10 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documento', '0001_initial'),
        ('detalle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.documento'),
        ),
    ]
