# Generated by Django 3.0.4 on 2020-03-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle', '0002_detalle_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='documento',
        ),
    ]
